name: Check MR

on: [pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v4
        with:
          +: task
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run mypy
        # For example, using `pytest`
        run: uv run mypy
