name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # renovate: datasource=github-releases depName=astral-sh/uv
          version: "0.7.2"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pytest
        run: uv run pytest .

      - name: Run --version
        run: uv run python toogoodtogo_ha_mqtt_bridge/main.py --version
